### ISSUE TITLE
Add some documentation on the koa-smart error handling

### ISSUE THREAD

**Issue by SakiiR** [ysocorp/koa-smart#2]
It would be great if you could add some documentation about how koa-smart is handling errors and how to throw inside a route.

**Comment by jeanclaudeyalap** [comment]
Hi @SakiiR , on the documentation (https://ysocorp.github.io/koa-smart/class/src/routes/Route.js~Route.html) you can see 5 functions to throw inside a route : 

1. `throw(status: number, error: string | object, translate: boolean): `
    throws a formated error to be caught.
2. `throwBadRequest(error: string | object, translate: boolean):`
    same as throw, but automatically sets the status to 400 BAD REQUEST
3. `throwForbidden(error: string | object, translate: boolean):`
    same as throw, but automatically sets the status to 403 FORBIDDEN
4. `throwNotFound(error: string | object, translate: boolean):`
    same as throw, but automatically sets the status to 404 NOT FOUND
5. `throwUnauthorized(error: string | object, translate: boolean):`
    same as throw, but automatically sets the status to 401 UNAUTHORIZED


you can use them on the route with `this.functionName`. 
eg : `this.throwNotFound()`
